name: Extract Info from HTML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  extract_info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests

    - name: Download HTML file
      run: |
        python extract_info.py  # 直接运行 Python 脚本，下载 HTML 文件
      env:
        CLIENT_ID: ${{ secrets.luogu_cookie }}
        UID: ${{ secrets.luogu_uid }}

    - name: Show HTML content
      run: |
        # 检查文件是否存在
        if [ -f "document.html" ]; then
          echo "文件内容 (前 1000 字符):"
          # 输出文件前 1000 字符，防止文件过大
          head -c 1000 document.html
        else
          echo "document.html 文件不存在。"
        fi
