name: Extract Info from HTML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  extract_info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests

    - name: Download HTML file
      run: |
        python -c "from extract_info import download_html; download_html(os.getenv('CLIENT_ID'), os.getenv('UID'))"
      env:
        CLIENT_ID: ${{ secrets.client_id }}
        UID: ${{ secrets._uid }}

    - name: Run Python script
      run: |
        python get_info.py  # 你的脚本文件名
