name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  issues: 
    types: 
      - opened
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print issue details
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Issue URL: ${{ github.event.issue.html_url }}"
      - name: compile
        run: g++ -g focus.cpp -o focus -std=c++14
      - name: run
        run: ./focus
      - name: Display log.log contents
        run: cat log.log  
