name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  issues: 
    types: 
      - opened
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print issue details
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Issue URL: ${{ github.event.issue.html_url }}"
      - name: install curlib
        run: sudo apt-get install libcurl4-openssl-dev
      - name: compile
        run: g++ -g focus.cpp -o focus -std=c++17
      - name: Run C++ program
        env:
          luogu_cookie: ${{ secrets.luogu_cookie }}
          luogu_uid: ${{ secrets.luogu_uid }}
          uid: ${{github.event.issue.body}}
        run: ./focus
